const studentList = [
  { github: "andyschachter", slack: "U01NMC0SZ27" },
  { github: "annie-i0", slack: "U01NECMJMJS" },
  { github: "smithci1", slack: "U01NMC0DDQB" },
  { github: "bellusvulpes", slack: "U01PB1A0Q64" },
  { github: "Danielamoateng1989", slack: "U01N6CNM8GP" },
  { github: "davepenaloza", slack: "U01NMC0FBFV" },
  { github: "firizarry-coder", slack: "U01PFUUJY8G" },
  { github: "gioaceto", slack: "U01NJ6LMVNJ" },
  { github: "jeraldina", slack: "U01NECMLJKG" },
  { github: "grimmi5894", slack: "U01NECMNP54" },
  { github: "keefers1030", slack: "U01NMC0USAF" },
  { github: "kolbycamp211", slack: "U01NMC16NUT" },
  { github: "lamsa01", slack: "U01NMC12ZB5" },
  { github: "mardany126", slack: "U01NECMDXE2" },
  { github: "misheline", slack: "U01NMC0PD51" },
  { github: "oaklanz", slack: "U01NMC0LBBM" },
  { github: "robinmalkus", slack: "U01NQUVF85Q" },
  { github: "pathou80", slack: "U01PB1ATD5W" },
  { github: "larocque-m", slack: "U01NECKHL4E" },
  { github: "markh82581", slack: "U01NMC0GUV9" },
  { github: "marnie-k", slack: "U01NMC0GUV9" },
  // { github: "hollisjamison", slack: "U01NMC0RD3M" },
  // { github: "mikaelacurrier", slack: "U01N6CM60UX" },
  // { github: "sebastian-vivas", slack: "U01NECMH4T0" },
  // { github: "carryegaulin31", slack: "U01NMC014P5" },
];

module.exports = {
  studentList,
};
